apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ie82t7izk-go
  janus-idp.io/tekton: ie82t7izk-go
  backstage.io/kubernetes-id: ie82t7izk-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ie82t7izk-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
