apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ie82t7izk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ie82t7izk-go 
  name: ie82t7izk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ie82t7izk-go 
